# bind the cert-manager internal approver to approve
# certmanager.step.sm CertificateRequests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-controller-approve:certmanager-step-sm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-controller-approve:certmanager-step-sm
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
