# permissions to approve all certmanager.step.sm requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:certmanager-step-sm
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - signers
  verbs:
  - approve
  resourceNames:
  - stepissuers.certmanager.step.sm/*
  - stepclusterissuers.certmanager.step.sm/*
